services:
  - type: web
    name: tarowhisper-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    pythonVersion: 3.10.12  # ← ключевая строка
    envVars:
      - key: BOT_TOKEN
        sync: false
